services:

  recipes:
    image: recipes
    ports:
      - 3000:3000
    links:
      - mongoRecipes
    depends_on:
      - mongoRecipes
    env_file: ./.env
    networks:
      - node-webapp-network

  mongoRecipes:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge