services:

  commands:
    build:
      dockerfile: Dockerfile_dev
    links:
      - mongoDB
    depends_on:
      - mongoDB
    env_file: ./.env
    networks:
      - node-webapp-network
  recipes:
    build: .
    ports:
      - 3000:3000
    links:
      - mongoDB
    depends_on:
      - mongoDB
    env_file: ./.env
    networks:
      - node-webapp-network

  mongoDB:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge